name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true
    
    - name: Setup Go environment
      uses: actions/setup-go@v2
      
    - name: Check Go version
      run: go version
    
    - name: Hugo Deploy GitHub Pages
      uses: bhargavkathivarapu/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.69.1
        TARGET_REPO: bhargavkathivarapu/bhargavkathivarapu.github.io
        TOKEN: ${{ secrets.TOKEN }}
        CNAME: bhargavkathivarapu.github.io
        GO111MODULE: on
